// Generated by gencpp from file global_planner/PathWithRiskMsg.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANNER_MESSAGE_PATHWITHRISKMSG_H
#define GLOBAL_PLANNER_MESSAGE_PATHWITHRISKMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace global_planner
{
template <class ContainerAllocator>
struct PathWithRiskMsg_
{
  typedef PathWithRiskMsg_<ContainerAllocator> Type;

  PathWithRiskMsg_()
    : header()
    , poses()
    , risks()  {
    }
  PathWithRiskMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)
    , risks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _risks_type;
  _risks_type risks;





  typedef boost::shared_ptr< ::global_planner::PathWithRiskMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_planner::PathWithRiskMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PathWithRiskMsg_

typedef ::global_planner::PathWithRiskMsg_<std::allocator<void> > PathWithRiskMsg;

typedef boost::shared_ptr< ::global_planner::PathWithRiskMsg > PathWithRiskMsgPtr;
typedef boost::shared_ptr< ::global_planner::PathWithRiskMsg const> PathWithRiskMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_planner::PathWithRiskMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::global_planner::PathWithRiskMsg_<ContainerAllocator1> & lhs, const ::global_planner::PathWithRiskMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.poses == rhs.poses &&
    lhs.risks == rhs.risks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::global_planner::PathWithRiskMsg_<ContainerAllocator1> & lhs, const ::global_planner::PathWithRiskMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace global_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_planner::PathWithRiskMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_planner::PathWithRiskMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_planner::PathWithRiskMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e128811a901103e165991579467bdd5f";
  }

  static const char* value(const ::global_planner::PathWithRiskMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe128811a901103e1ULL;
  static const uint64_t static_value2 = 0x65991579467bdd5fULL;
};

template<class ContainerAllocator>
struct DataType< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_planner/PathWithRiskMsg";
  }

  static const char* value(const ::global_planner::PathWithRiskMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"float64[] risks\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::global_planner::PathWithRiskMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
      stream.next(m.risks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathWithRiskMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_planner::PathWithRiskMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_planner::PathWithRiskMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "risks[]" << std::endl;
    for (size_t i = 0; i < v.risks.size(); ++i)
    {
      s << indent << "  risks[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.risks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_PLANNER_MESSAGE_PATHWITHRISKMSG_H
