//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the avoidance package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __avoidance__LOCALPLANNERNODECONFIG_H__
#define __avoidance__LOCALPLANNERNODECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace avoidance
{
  class LocalPlannerNodeConfigStatics;

  class LocalPlannerNodeConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(LocalPlannerNodeConfig &config, const LocalPlannerNodeConfig &max, const LocalPlannerNodeConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LocalPlannerNodeConfig &config1, const LocalPlannerNodeConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LocalPlannerNodeConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LocalPlannerNodeConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LocalPlannerNodeConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LocalPlannerNodeConfig &config) const = 0;
      virtual void getValue(const LocalPlannerNodeConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LocalPlannerNodeConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T LocalPlannerNodeConfig::* field;

      virtual void clamp(LocalPlannerNodeConfig &config, const LocalPlannerNodeConfig &max, const LocalPlannerNodeConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LocalPlannerNodeConfig &config1, const LocalPlannerNodeConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LocalPlannerNodeConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LocalPlannerNodeConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LocalPlannerNodeConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LocalPlannerNodeConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LocalPlannerNodeConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LocalPlannerNodeConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LocalPlannerNodeConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<LocalPlannerNodeConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LocalPlannerNodeConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_sensor_range_"==(*_i)->name){max_sensor_range_ = boost::any_cast<double>(val);}
        if("min_sensor_range_"==(*_i)->name){min_sensor_range_ = boost::any_cast<double>(val);}
        if("pitch_cost_param_"==(*_i)->name){pitch_cost_param_ = boost::any_cast<double>(val);}
        if("yaw_cost_param_"==(*_i)->name){yaw_cost_param_ = boost::any_cast<double>(val);}
        if("velocity_cost_param_"==(*_i)->name){velocity_cost_param_ = boost::any_cast<double>(val);}
        if("obstacle_cost_param_"==(*_i)->name){obstacle_cost_param_ = boost::any_cast<double>(val);}
        if("tree_heuristic_weight_"==(*_i)->name){tree_heuristic_weight_ = boost::any_cast<double>(val);}
        if("goal_z_param"==(*_i)->name){goal_z_param = boost::any_cast<double>(val);}
        if("timeout_startup_"==(*_i)->name){timeout_startup_ = boost::any_cast<double>(val);}
        if("timeout_critical_"==(*_i)->name){timeout_critical_ = boost::any_cast<double>(val);}
        if("timeout_termination_"==(*_i)->name){timeout_termination_ = boost::any_cast<double>(val);}
        if("max_point_age_s_"==(*_i)->name){max_point_age_s_ = boost::any_cast<double>(val);}
        if("min_num_points_per_cell_"==(*_i)->name){min_num_points_per_cell_ = boost::any_cast<int>(val);}
        if("smoothing_speed_xy_"==(*_i)->name){smoothing_speed_xy_ = boost::any_cast<double>(val);}
        if("smoothing_speed_z_"==(*_i)->name){smoothing_speed_z_ = boost::any_cast<double>(val);}
        if("smoothing_margin_degrees_"==(*_i)->name){smoothing_margin_degrees_ = boost::any_cast<double>(val);}
        if("children_per_node_"==(*_i)->name){children_per_node_ = boost::any_cast<int>(val);}
        if("n_expanded_nodes_"==(*_i)->name){n_expanded_nodes_ = boost::any_cast<int>(val);}
        if("tree_node_distance_"==(*_i)->name){tree_node_distance_ = boost::any_cast<double>(val);}
      }
    }

    double max_sensor_range_;
double min_sensor_range_;
double pitch_cost_param_;
double yaw_cost_param_;
double velocity_cost_param_;
double obstacle_cost_param_;
double tree_heuristic_weight_;
double goal_z_param;
double timeout_startup_;
double timeout_critical_;
double timeout_termination_;
double max_point_age_s_;
int min_num_points_per_cell_;
double smoothing_speed_xy_;
double smoothing_speed_z_;
double smoothing_margin_degrees_;
int children_per_node_;
int n_expanded_nodes_;
double tree_node_distance_;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_sensor_range_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_sensor_range_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pitch_cost_param_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_cost_param_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velocity_cost_param_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double obstacle_cost_param_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tree_heuristic_weight_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_z_param;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double timeout_startup_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double timeout_critical_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double timeout_termination_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_point_age_s_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_num_points_per_cell_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double smoothing_speed_xy_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double smoothing_speed_z_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double smoothing_margin_degrees_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int children_per_node_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int n_expanded_nodes_;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tree_node_distance_;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LocalPlannerNodeConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LocalPlannerNodeConfig &__max__ = __getMax__();
      const LocalPlannerNodeConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LocalPlannerNodeConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LocalPlannerNodeConfig &__getDefault__();
    static const LocalPlannerNodeConfig &__getMax__();
    static const LocalPlannerNodeConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LocalPlannerNodeConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LocalPlannerNodeConfig::ParamDescription<std::string>::clamp(LocalPlannerNodeConfig &config, const LocalPlannerNodeConfig &max, const LocalPlannerNodeConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LocalPlannerNodeConfigStatics
  {
    friend class LocalPlannerNodeConfig;

    LocalPlannerNodeConfigStatics()
    {
LocalPlannerNodeConfig::GroupDescription<LocalPlannerNodeConfig::DEFAULT, LocalPlannerNodeConfig> Default("Default", "", 0, 0, true, &LocalPlannerNodeConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_sensor_range_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_sensor_range_ = 40.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_sensor_range_ = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("max_sensor_range_", "double", 0, "Data points farther away will be discarded", "", &LocalPlannerNodeConfig::max_sensor_range_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("max_sensor_range_", "double", 0, "Data points farther away will be discarded", "", &LocalPlannerNodeConfig::max_sensor_range_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_sensor_range_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_sensor_range_ = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_sensor_range_ = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("min_sensor_range_", "double", 0, "Discard points closer than that", "", &LocalPlannerNodeConfig::min_sensor_range_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("min_sensor_range_", "double", 0, "Discard points closer than that", "", &LocalPlannerNodeConfig::min_sensor_range_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pitch_cost_param_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pitch_cost_param_ = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pitch_cost_param_ = 25.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("pitch_cost_param_", "double", 0, "Cost function weight for goal oriented behavior", "", &LocalPlannerNodeConfig::pitch_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("pitch_cost_param_", "double", 0, "Cost function weight for goal oriented behavior", "", &LocalPlannerNodeConfig::pitch_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_cost_param_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_cost_param_ = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_cost_param_ = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("yaw_cost_param_", "double", 0, "Cost function weight for constant heading", "", &LocalPlannerNodeConfig::yaw_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("yaw_cost_param_", "double", 0, "Cost function weight for constant heading", "", &LocalPlannerNodeConfig::yaw_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velocity_cost_param_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velocity_cost_param_ = 50000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velocity_cost_param_ = 6000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("velocity_cost_param_", "double", 0, "Cost function weight for path smoothness", "", &LocalPlannerNodeConfig::velocity_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("velocity_cost_param_", "double", 0, "Cost function weight for path smoothness", "", &LocalPlannerNodeConfig::velocity_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.obstacle_cost_param_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.obstacle_cost_param_ = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.obstacle_cost_param_ = 8.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("obstacle_cost_param_", "double", 0, "Approximate distance from obstacles (m) when the obstacle distance term dominates the cost function", "", &LocalPlannerNodeConfig::obstacle_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("obstacle_cost_param_", "double", 0, "Approximate distance from obstacles (m) when the obstacle distance term dominates the cost function", "", &LocalPlannerNodeConfig::obstacle_cost_param_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tree_heuristic_weight_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tree_heuristic_weight_ = 50.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tree_heuristic_weight_ = 35.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("tree_heuristic_weight_", "double", 0, "Weight for the tree heuristic cost", "", &LocalPlannerNodeConfig::tree_heuristic_weight_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("tree_heuristic_weight_", "double", 0, "Weight for the tree heuristic cost", "", &LocalPlannerNodeConfig::tree_heuristic_weight_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_z_param = -20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_z_param = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_z_param = 3.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("goal_z_param", "double", 0, "Height of the goal position", "", &LocalPlannerNodeConfig::goal_z_param)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("goal_z_param", "double", 0, "Height of the goal position", "", &LocalPlannerNodeConfig::goal_z_param)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.timeout_startup_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.timeout_startup_ = 60.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.timeout_startup_ = 5.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_startup_", "double", 0, "After this timeout the companion status is MAV_STATE_CRITICAL", "", &LocalPlannerNodeConfig::timeout_startup_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_startup_", "double", 0, "After this timeout the companion status is MAV_STATE_CRITICAL", "", &LocalPlannerNodeConfig::timeout_startup_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.timeout_critical_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.timeout_critical_ = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.timeout_critical_ = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_critical_", "double", 0, "After this timeout the companion status is MAV_STATE_CRITICAL", "", &LocalPlannerNodeConfig::timeout_critical_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_critical_", "double", 0, "After this timeout the companion status is MAV_STATE_CRITICAL", "", &LocalPlannerNodeConfig::timeout_critical_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.timeout_termination_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.timeout_termination_ = 1000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.timeout_termination_ = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_termination_", "double", 0, "After this timeout the companion status is MAV_STATE_FLIGHT_TERMINATION", "", &LocalPlannerNodeConfig::timeout_termination_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("timeout_termination_", "double", 0, "After this timeout the companion status is MAV_STATE_FLIGHT_TERMINATION", "", &LocalPlannerNodeConfig::timeout_termination_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_point_age_s_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_point_age_s_ = 500.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_point_age_s_ = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("max_point_age_s_", "double", 0, "maximum age of a remembered data point", "", &LocalPlannerNodeConfig::max_point_age_s_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("max_point_age_s_", "double", 0, "maximum age of a remembered data point", "", &LocalPlannerNodeConfig::max_point_age_s_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_num_points_per_cell_ = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_num_points_per_cell_ = 500;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_num_points_per_cell_ = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("min_num_points_per_cell_", "int", 0, "minimum number of points in one area to be kept, if lower they are discarded as noise", "", &LocalPlannerNodeConfig::min_num_points_per_cell_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("min_num_points_per_cell_", "int", 0, "minimum number of points in one area to be kept, if lower they are discarded as noise", "", &LocalPlannerNodeConfig::min_num_points_per_cell_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.smoothing_speed_xy_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.smoothing_speed_xy_ = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.smoothing_speed_xy_ = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_speed_xy_", "double", 0, "response speed of the smoothing system in xy (set to 0 to disable)", "", &LocalPlannerNodeConfig::smoothing_speed_xy_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_speed_xy_", "double", 0, "response speed of the smoothing system in xy (set to 0 to disable)", "", &LocalPlannerNodeConfig::smoothing_speed_xy_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.smoothing_speed_z_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.smoothing_speed_z_ = 30.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.smoothing_speed_z_ = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_speed_z_", "double", 0, "response speed of the smoothing system in z (set to 0 to disable)", "", &LocalPlannerNodeConfig::smoothing_speed_z_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_speed_z_", "double", 0, "response speed of the smoothing system in z (set to 0 to disable)", "", &LocalPlannerNodeConfig::smoothing_speed_z_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.smoothing_margin_degrees_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.smoothing_margin_degrees_ = 90.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.smoothing_margin_degrees_ = 40.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_margin_degrees_", "double", 0, "smoothing radius for obstacle cost in cost histogram", "", &LocalPlannerNodeConfig::smoothing_margin_degrees_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("smoothing_margin_degrees_", "double", 0, "smoothing radius for obstacle cost in cost histogram", "", &LocalPlannerNodeConfig::smoothing_margin_degrees_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.children_per_node_ = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.children_per_node_ = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.children_per_node_ = 8;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("children_per_node_", "int", 0, "Branching factor of the search tree", "", &LocalPlannerNodeConfig::children_per_node_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("children_per_node_", "int", 0, "Branching factor of the search tree", "", &LocalPlannerNodeConfig::children_per_node_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.n_expanded_nodes_ = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.n_expanded_nodes_ = 200;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.n_expanded_nodes_ = 40;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("n_expanded_nodes_", "int", 0, "Number of nodes expanded in complete tree", "", &LocalPlannerNodeConfig::n_expanded_nodes_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<int>("n_expanded_nodes_", "int", 0, "Number of nodes expanded in complete tree", "", &LocalPlannerNodeConfig::n_expanded_nodes_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tree_node_distance_ = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tree_node_distance_ = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tree_node_distance_ = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("tree_node_distance_", "double", 0, "Distance between nodes", "", &LocalPlannerNodeConfig::tree_node_distance_)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr(new LocalPlannerNodeConfig::ParamDescription<double>("tree_node_distance_", "double", 0, "Distance between nodes", "", &LocalPlannerNodeConfig::tree_node_distance_)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LocalPlannerNodeConfig::AbstractGroupDescriptionConstPtr(new LocalPlannerNodeConfig::GroupDescription<LocalPlannerNodeConfig::DEFAULT, LocalPlannerNodeConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LocalPlannerNodeConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LocalPlannerNodeConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LocalPlannerNodeConfig __max__;
    LocalPlannerNodeConfig __min__;
    LocalPlannerNodeConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LocalPlannerNodeConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LocalPlannerNodeConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LocalPlannerNodeConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LocalPlannerNodeConfig &LocalPlannerNodeConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LocalPlannerNodeConfig &LocalPlannerNodeConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LocalPlannerNodeConfig &LocalPlannerNodeConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LocalPlannerNodeConfig::AbstractParamDescriptionConstPtr> &LocalPlannerNodeConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LocalPlannerNodeConfig::AbstractGroupDescriptionConstPtr> &LocalPlannerNodeConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LocalPlannerNodeConfigStatics *LocalPlannerNodeConfig::__get_statics__()
  {
    const static LocalPlannerNodeConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LocalPlannerNodeConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LOCALPLANNERNODERECONFIGURATOR_H__
