# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_check/PlotDataMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class PlotDataMsg(genpy.Message):
  _md5sum = "34437636d1c86e0bba868e7bc32517df"
  _type = "msg_check/PlotDataMsg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Vector3 sp
geometry_msgs/Vector3 sq
geometry_msgs/Vector3 acceleration
geometry_msgs/Vector3 angular_acceleration
geometry_msgs/Vector3 position_error
geometry_msgs/Vector3 velocity_error
geometry_msgs/Vector3 position_error_integral
geometry_msgs/Vector3 angle_error
geometry_msgs/Vector3 angle_rate_error
geometry_msgs/Vector3 Kp_hat
geometry_msgs/Vector3 Kq_hat_0
geometry_msgs/Vector3 Kq_hat_1
geometry_msgs/Vector3 Kq_hat_2
geometry_msgs/Vector3 rho_p
geometry_msgs/Vector3 rho_q
geometry_msgs/Vector3 delTau_p
geometry_msgs/Vector3 delTau_q
geometry_msgs/Vector3 moments
float64 thrust
float64 M_hat

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','sp','sq','acceleration','angular_acceleration','position_error','velocity_error','position_error_integral','angle_error','angle_rate_error','Kp_hat','Kq_hat_0','Kq_hat_1','Kq_hat_2','rho_p','rho_q','delTau_p','delTau_q','moments','thrust','M_hat']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,sp,sq,acceleration,angular_acceleration,position_error,velocity_error,position_error_integral,angle_error,angle_rate_error,Kp_hat,Kq_hat_0,Kq_hat_1,Kq_hat_2,rho_p,rho_q,delTau_p,delTau_q,moments,thrust,M_hat

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlotDataMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sp is None:
        self.sp = geometry_msgs.msg.Vector3()
      if self.sq is None:
        self.sq = geometry_msgs.msg.Vector3()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.angular_acceleration is None:
        self.angular_acceleration = geometry_msgs.msg.Vector3()
      if self.position_error is None:
        self.position_error = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.position_error_integral is None:
        self.position_error_integral = geometry_msgs.msg.Vector3()
      if self.angle_error is None:
        self.angle_error = geometry_msgs.msg.Vector3()
      if self.angle_rate_error is None:
        self.angle_rate_error = geometry_msgs.msg.Vector3()
      if self.Kp_hat is None:
        self.Kp_hat = geometry_msgs.msg.Vector3()
      if self.Kq_hat_0 is None:
        self.Kq_hat_0 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_1 is None:
        self.Kq_hat_1 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_2 is None:
        self.Kq_hat_2 = geometry_msgs.msg.Vector3()
      if self.rho_p is None:
        self.rho_p = geometry_msgs.msg.Vector3()
      if self.rho_q is None:
        self.rho_q = geometry_msgs.msg.Vector3()
      if self.delTau_p is None:
        self.delTau_p = geometry_msgs.msg.Vector3()
      if self.delTau_q is None:
        self.delTau_q = geometry_msgs.msg.Vector3()
      if self.moments is None:
        self.moments = geometry_msgs.msg.Vector3()
      if self.thrust is None:
        self.thrust = 0.
      if self.M_hat is None:
        self.M_hat = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.sp = geometry_msgs.msg.Vector3()
      self.sq = geometry_msgs.msg.Vector3()
      self.acceleration = geometry_msgs.msg.Vector3()
      self.angular_acceleration = geometry_msgs.msg.Vector3()
      self.position_error = geometry_msgs.msg.Vector3()
      self.velocity_error = geometry_msgs.msg.Vector3()
      self.position_error_integral = geometry_msgs.msg.Vector3()
      self.angle_error = geometry_msgs.msg.Vector3()
      self.angle_rate_error = geometry_msgs.msg.Vector3()
      self.Kp_hat = geometry_msgs.msg.Vector3()
      self.Kq_hat_0 = geometry_msgs.msg.Vector3()
      self.Kq_hat_1 = geometry_msgs.msg.Vector3()
      self.Kq_hat_2 = geometry_msgs.msg.Vector3()
      self.rho_p = geometry_msgs.msg.Vector3()
      self.rho_q = geometry_msgs.msg.Vector3()
      self.delTau_p = geometry_msgs.msg.Vector3()
      self.delTau_q = geometry_msgs.msg.Vector3()
      self.moments = geometry_msgs.msg.Vector3()
      self.thrust = 0.
      self.M_hat = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_56d().pack(_x.sp.x, _x.sp.y, _x.sp.z, _x.sq.x, _x.sq.y, _x.sq.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.angular_acceleration.x, _x.angular_acceleration.y, _x.angular_acceleration.z, _x.position_error.x, _x.position_error.y, _x.position_error.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z, _x.position_error_integral.x, _x.position_error_integral.y, _x.position_error_integral.z, _x.angle_error.x, _x.angle_error.y, _x.angle_error.z, _x.angle_rate_error.x, _x.angle_rate_error.y, _x.angle_rate_error.z, _x.Kp_hat.x, _x.Kp_hat.y, _x.Kp_hat.z, _x.Kq_hat_0.x, _x.Kq_hat_0.y, _x.Kq_hat_0.z, _x.Kq_hat_1.x, _x.Kq_hat_1.y, _x.Kq_hat_1.z, _x.Kq_hat_2.x, _x.Kq_hat_2.y, _x.Kq_hat_2.z, _x.rho_p.x, _x.rho_p.y, _x.rho_p.z, _x.rho_q.x, _x.rho_q.y, _x.rho_q.z, _x.delTau_p.x, _x.delTau_p.y, _x.delTau_p.z, _x.delTau_q.x, _x.delTau_q.y, _x.delTau_q.z, _x.moments.x, _x.moments.y, _x.moments.z, _x.thrust, _x.M_hat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sp is None:
        self.sp = geometry_msgs.msg.Vector3()
      if self.sq is None:
        self.sq = geometry_msgs.msg.Vector3()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.angular_acceleration is None:
        self.angular_acceleration = geometry_msgs.msg.Vector3()
      if self.position_error is None:
        self.position_error = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.position_error_integral is None:
        self.position_error_integral = geometry_msgs.msg.Vector3()
      if self.angle_error is None:
        self.angle_error = geometry_msgs.msg.Vector3()
      if self.angle_rate_error is None:
        self.angle_rate_error = geometry_msgs.msg.Vector3()
      if self.Kp_hat is None:
        self.Kp_hat = geometry_msgs.msg.Vector3()
      if self.Kq_hat_0 is None:
        self.Kq_hat_0 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_1 is None:
        self.Kq_hat_1 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_2 is None:
        self.Kq_hat_2 = geometry_msgs.msg.Vector3()
      if self.rho_p is None:
        self.rho_p = geometry_msgs.msg.Vector3()
      if self.rho_q is None:
        self.rho_q = geometry_msgs.msg.Vector3()
      if self.delTau_p is None:
        self.delTau_p = geometry_msgs.msg.Vector3()
      if self.delTau_q is None:
        self.delTau_q = geometry_msgs.msg.Vector3()
      if self.moments is None:
        self.moments = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 448
      (_x.sp.x, _x.sp.y, _x.sp.z, _x.sq.x, _x.sq.y, _x.sq.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.angular_acceleration.x, _x.angular_acceleration.y, _x.angular_acceleration.z, _x.position_error.x, _x.position_error.y, _x.position_error.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z, _x.position_error_integral.x, _x.position_error_integral.y, _x.position_error_integral.z, _x.angle_error.x, _x.angle_error.y, _x.angle_error.z, _x.angle_rate_error.x, _x.angle_rate_error.y, _x.angle_rate_error.z, _x.Kp_hat.x, _x.Kp_hat.y, _x.Kp_hat.z, _x.Kq_hat_0.x, _x.Kq_hat_0.y, _x.Kq_hat_0.z, _x.Kq_hat_1.x, _x.Kq_hat_1.y, _x.Kq_hat_1.z, _x.Kq_hat_2.x, _x.Kq_hat_2.y, _x.Kq_hat_2.z, _x.rho_p.x, _x.rho_p.y, _x.rho_p.z, _x.rho_q.x, _x.rho_q.y, _x.rho_q.z, _x.delTau_p.x, _x.delTau_p.y, _x.delTau_p.z, _x.delTau_q.x, _x.delTau_q.y, _x.delTau_q.z, _x.moments.x, _x.moments.y, _x.moments.z, _x.thrust, _x.M_hat,) = _get_struct_56d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_56d().pack(_x.sp.x, _x.sp.y, _x.sp.z, _x.sq.x, _x.sq.y, _x.sq.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.angular_acceleration.x, _x.angular_acceleration.y, _x.angular_acceleration.z, _x.position_error.x, _x.position_error.y, _x.position_error.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z, _x.position_error_integral.x, _x.position_error_integral.y, _x.position_error_integral.z, _x.angle_error.x, _x.angle_error.y, _x.angle_error.z, _x.angle_rate_error.x, _x.angle_rate_error.y, _x.angle_rate_error.z, _x.Kp_hat.x, _x.Kp_hat.y, _x.Kp_hat.z, _x.Kq_hat_0.x, _x.Kq_hat_0.y, _x.Kq_hat_0.z, _x.Kq_hat_1.x, _x.Kq_hat_1.y, _x.Kq_hat_1.z, _x.Kq_hat_2.x, _x.Kq_hat_2.y, _x.Kq_hat_2.z, _x.rho_p.x, _x.rho_p.y, _x.rho_p.z, _x.rho_q.x, _x.rho_q.y, _x.rho_q.z, _x.delTau_p.x, _x.delTau_p.y, _x.delTau_p.z, _x.delTau_q.x, _x.delTau_q.y, _x.delTau_q.z, _x.moments.x, _x.moments.y, _x.moments.z, _x.thrust, _x.M_hat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sp is None:
        self.sp = geometry_msgs.msg.Vector3()
      if self.sq is None:
        self.sq = geometry_msgs.msg.Vector3()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.angular_acceleration is None:
        self.angular_acceleration = geometry_msgs.msg.Vector3()
      if self.position_error is None:
        self.position_error = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.position_error_integral is None:
        self.position_error_integral = geometry_msgs.msg.Vector3()
      if self.angle_error is None:
        self.angle_error = geometry_msgs.msg.Vector3()
      if self.angle_rate_error is None:
        self.angle_rate_error = geometry_msgs.msg.Vector3()
      if self.Kp_hat is None:
        self.Kp_hat = geometry_msgs.msg.Vector3()
      if self.Kq_hat_0 is None:
        self.Kq_hat_0 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_1 is None:
        self.Kq_hat_1 = geometry_msgs.msg.Vector3()
      if self.Kq_hat_2 is None:
        self.Kq_hat_2 = geometry_msgs.msg.Vector3()
      if self.rho_p is None:
        self.rho_p = geometry_msgs.msg.Vector3()
      if self.rho_q is None:
        self.rho_q = geometry_msgs.msg.Vector3()
      if self.delTau_p is None:
        self.delTau_p = geometry_msgs.msg.Vector3()
      if self.delTau_q is None:
        self.delTau_q = geometry_msgs.msg.Vector3()
      if self.moments is None:
        self.moments = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 448
      (_x.sp.x, _x.sp.y, _x.sp.z, _x.sq.x, _x.sq.y, _x.sq.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.angular_acceleration.x, _x.angular_acceleration.y, _x.angular_acceleration.z, _x.position_error.x, _x.position_error.y, _x.position_error.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z, _x.position_error_integral.x, _x.position_error_integral.y, _x.position_error_integral.z, _x.angle_error.x, _x.angle_error.y, _x.angle_error.z, _x.angle_rate_error.x, _x.angle_rate_error.y, _x.angle_rate_error.z, _x.Kp_hat.x, _x.Kp_hat.y, _x.Kp_hat.z, _x.Kq_hat_0.x, _x.Kq_hat_0.y, _x.Kq_hat_0.z, _x.Kq_hat_1.x, _x.Kq_hat_1.y, _x.Kq_hat_1.z, _x.Kq_hat_2.x, _x.Kq_hat_2.y, _x.Kq_hat_2.z, _x.rho_p.x, _x.rho_p.y, _x.rho_p.z, _x.rho_q.x, _x.rho_q.y, _x.rho_q.z, _x.delTau_p.x, _x.delTau_p.y, _x.delTau_p.z, _x.delTau_q.x, _x.delTau_q.y, _x.delTau_q.z, _x.moments.x, _x.moments.y, _x.moments.z, _x.thrust, _x.M_hat,) = _get_struct_56d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_56d = None
def _get_struct_56d():
    global _struct_56d
    if _struct_56d is None:
        _struct_56d = struct.Struct("<56d")
    return _struct_56d
