// Generated by gencpp from file geographic_msgs/GetGeoPathRequest.msg
// DO NOT EDIT!


#ifndef GEOGRAPHIC_MSGS_MESSAGE_GETGEOPATHREQUEST_H
#define GEOGRAPHIC_MSGS_MESSAGE_GETGEOPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geographic_msgs/GeoPoint.h>
#include <geographic_msgs/GeoPoint.h>

namespace geographic_msgs
{
template <class ContainerAllocator>
struct GetGeoPathRequest_
{
  typedef GetGeoPathRequest_<ContainerAllocator> Type;

  GetGeoPathRequest_()
    : start()
    , goal()  {
    }
  GetGeoPathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGeoPathRequest_

typedef ::geographic_msgs::GetGeoPathRequest_<std::allocator<void> > GetGeoPathRequest;

typedef boost::shared_ptr< ::geographic_msgs::GetGeoPathRequest > GetGeoPathRequestPtr;
typedef boost::shared_ptr< ::geographic_msgs::GetGeoPathRequest const> GetGeoPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator1> & lhs, const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator1> & lhs, const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace geographic_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cad6de11e4ae4ca568785186e1f99f89";
  }

  static const char* value(const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcad6de11e4ae4ca5ULL;
  static const uint64_t static_value2 = 0x68785186e1f99f89ULL;
};

template<class ContainerAllocator>
struct DataType< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geographic_msgs/GetGeoPathRequest";
  }

  static const char* value(const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Searches for given start and goal the nearest route segments\n"
"# and determine the path through the RouteNetwork\n"
"\n"
"geographic_msgs/GeoPoint start        # starting point\n"
"geographic_msgs/GeoPoint goal         # goal point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGeoPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geographic_msgs::GetGeoPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOGRAPHIC_MSGS_MESSAGE_GETGEOPATHREQUEST_H
