// Generated by gencpp from file geographic_msgs/GetGeographicMap.msg
// DO NOT EDIT!


#ifndef GEOGRAPHIC_MSGS_MESSAGE_GETGEOGRAPHICMAP_H
#define GEOGRAPHIC_MSGS_MESSAGE_GETGEOGRAPHICMAP_H

#include <ros/service_traits.h>


#include <geographic_msgs/GetGeographicMapRequest.h>
#include <geographic_msgs/GetGeographicMapResponse.h>


namespace geographic_msgs
{

struct GetGeographicMap
{

typedef GetGeographicMapRequest Request;
typedef GetGeographicMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGeographicMap
} // namespace geographic_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geographic_msgs::GetGeographicMap > {
  static const char* value()
  {
    return "c0278e653eee0ad79600510650e7be39";
  }

  static const char* value(const ::geographic_msgs::GetGeographicMap&) { return value(); }
};

template<>
struct DataType< ::geographic_msgs::GetGeographicMap > {
  static const char* value()
  {
    return "geographic_msgs/GetGeographicMap";
  }

  static const char* value(const ::geographic_msgs::GetGeographicMap&) { return value(); }
};


// service_traits::MD5Sum< ::geographic_msgs::GetGeographicMapRequest> should match
// service_traits::MD5Sum< ::geographic_msgs::GetGeographicMap >
template<>
struct MD5Sum< ::geographic_msgs::GetGeographicMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geographic_msgs::GetGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::GetGeographicMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geographic_msgs::GetGeographicMapRequest> should match
// service_traits::DataType< ::geographic_msgs::GetGeographicMap >
template<>
struct DataType< ::geographic_msgs::GetGeographicMapRequest>
{
  static const char* value()
  {
    return DataType< ::geographic_msgs::GetGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::GetGeographicMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geographic_msgs::GetGeographicMapResponse> should match
// service_traits::MD5Sum< ::geographic_msgs::GetGeographicMap >
template<>
struct MD5Sum< ::geographic_msgs::GetGeographicMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geographic_msgs::GetGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::GetGeographicMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geographic_msgs::GetGeographicMapResponse> should match
// service_traits::DataType< ::geographic_msgs::GetGeographicMap >
template<>
struct DataType< ::geographic_msgs::GetGeographicMapResponse>
{
  static const char* value()
  {
    return DataType< ::geographic_msgs::GetGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::GetGeographicMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOGRAPHIC_MSGS_MESSAGE_GETGEOGRAPHICMAP_H
