// Generated by gencpp from file geographic_msgs/UpdateGeographicMap.msg
// DO NOT EDIT!


#ifndef GEOGRAPHIC_MSGS_MESSAGE_UPDATEGEOGRAPHICMAP_H
#define GEOGRAPHIC_MSGS_MESSAGE_UPDATEGEOGRAPHICMAP_H

#include <ros/service_traits.h>


#include <geographic_msgs/UpdateGeographicMapRequest.h>
#include <geographic_msgs/UpdateGeographicMapResponse.h>


namespace geographic_msgs
{

struct UpdateGeographicMap
{

typedef UpdateGeographicMapRequest Request;
typedef UpdateGeographicMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateGeographicMap
} // namespace geographic_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geographic_msgs::UpdateGeographicMap > {
  static const char* value()
  {
    return "93db3f1ec099e9f1b7e442d7d397e244";
  }

  static const char* value(const ::geographic_msgs::UpdateGeographicMap&) { return value(); }
};

template<>
struct DataType< ::geographic_msgs::UpdateGeographicMap > {
  static const char* value()
  {
    return "geographic_msgs/UpdateGeographicMap";
  }

  static const char* value(const ::geographic_msgs::UpdateGeographicMap&) { return value(); }
};


// service_traits::MD5Sum< ::geographic_msgs::UpdateGeographicMapRequest> should match
// service_traits::MD5Sum< ::geographic_msgs::UpdateGeographicMap >
template<>
struct MD5Sum< ::geographic_msgs::UpdateGeographicMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geographic_msgs::UpdateGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::UpdateGeographicMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geographic_msgs::UpdateGeographicMapRequest> should match
// service_traits::DataType< ::geographic_msgs::UpdateGeographicMap >
template<>
struct DataType< ::geographic_msgs::UpdateGeographicMapRequest>
{
  static const char* value()
  {
    return DataType< ::geographic_msgs::UpdateGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::UpdateGeographicMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geographic_msgs::UpdateGeographicMapResponse> should match
// service_traits::MD5Sum< ::geographic_msgs::UpdateGeographicMap >
template<>
struct MD5Sum< ::geographic_msgs::UpdateGeographicMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geographic_msgs::UpdateGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::UpdateGeographicMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geographic_msgs::UpdateGeographicMapResponse> should match
// service_traits::DataType< ::geographic_msgs::UpdateGeographicMap >
template<>
struct DataType< ::geographic_msgs::UpdateGeographicMapResponse>
{
  static const char* value()
  {
    return DataType< ::geographic_msgs::UpdateGeographicMap >::value();
  }
  static const char* value(const ::geographic_msgs::UpdateGeographicMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOGRAPHIC_MSGS_MESSAGE_UPDATEGEOGRAPHICMAP_H
