// Generated by gencpp from file msg_check/PlotDataMsg.msg
// DO NOT EDIT!


#ifndef MSG_CHECK_MESSAGE_PLOTDATAMSG_H
#define MSG_CHECK_MESSAGE_PLOTDATAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace msg_check
{
template <class ContainerAllocator>
struct PlotDataMsg_
{
  typedef PlotDataMsg_<ContainerAllocator> Type;

  PlotDataMsg_()
    : header()
    , sp()
    , sq()
    , acceleration()
    , angular_acceleration()
    , position_error()
    , velocity_error()
    , position_error_integral()
    , angle_error()
    , angle_rate_error()
    , Kp_hat()
    , Kq_hat_0()
    , Kq_hat_1()
    , Kq_hat_2()
    , rho_p()
    , rho_q()
    , delTau_p()
    , delTau_q()
    , moments()
    , thrust(0.0)
    , M_hat(0.0)  {
    }
  PlotDataMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sp(_alloc)
    , sq(_alloc)
    , acceleration(_alloc)
    , angular_acceleration(_alloc)
    , position_error(_alloc)
    , velocity_error(_alloc)
    , position_error_integral(_alloc)
    , angle_error(_alloc)
    , angle_rate_error(_alloc)
    , Kp_hat(_alloc)
    , Kq_hat_0(_alloc)
    , Kq_hat_1(_alloc)
    , Kq_hat_2(_alloc)
    , rho_p(_alloc)
    , rho_q(_alloc)
    , delTau_p(_alloc)
    , delTau_q(_alloc)
    , moments(_alloc)
    , thrust(0.0)
    , M_hat(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _sp_type;
  _sp_type sp;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _sq_type;
  _sq_type sq;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_acceleration_type;
  _angular_acceleration_type angular_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_error_type;
  _position_error_type position_error;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_error_type;
  _velocity_error_type velocity_error;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_error_integral_type;
  _position_error_integral_type position_error_integral;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angle_error_type;
  _angle_error_type angle_error;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angle_rate_error_type;
  _angle_rate_error_type angle_rate_error;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Kp_hat_type;
  _Kp_hat_type Kp_hat;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Kq_hat_0_type;
  _Kq_hat_0_type Kq_hat_0;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Kq_hat_1_type;
  _Kq_hat_1_type Kq_hat_1;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Kq_hat_2_type;
  _Kq_hat_2_type Kq_hat_2;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rho_p_type;
  _rho_p_type rho_p;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rho_q_type;
  _rho_q_type rho_q;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _delTau_p_type;
  _delTau_p_type delTau_p;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _delTau_q_type;
  _delTau_q_type delTau_q;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _moments_type;
  _moments_type moments;

   typedef double _thrust_type;
  _thrust_type thrust;

   typedef double _M_hat_type;
  _M_hat_type M_hat;





  typedef boost::shared_ptr< ::msg_check::PlotDataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_check::PlotDataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PlotDataMsg_

typedef ::msg_check::PlotDataMsg_<std::allocator<void> > PlotDataMsg;

typedef boost::shared_ptr< ::msg_check::PlotDataMsg > PlotDataMsgPtr;
typedef boost::shared_ptr< ::msg_check::PlotDataMsg const> PlotDataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_check::PlotDataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_check::PlotDataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_check::PlotDataMsg_<ContainerAllocator1> & lhs, const ::msg_check::PlotDataMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sp == rhs.sp &&
    lhs.sq == rhs.sq &&
    lhs.acceleration == rhs.acceleration &&
    lhs.angular_acceleration == rhs.angular_acceleration &&
    lhs.position_error == rhs.position_error &&
    lhs.velocity_error == rhs.velocity_error &&
    lhs.position_error_integral == rhs.position_error_integral &&
    lhs.angle_error == rhs.angle_error &&
    lhs.angle_rate_error == rhs.angle_rate_error &&
    lhs.Kp_hat == rhs.Kp_hat &&
    lhs.Kq_hat_0 == rhs.Kq_hat_0 &&
    lhs.Kq_hat_1 == rhs.Kq_hat_1 &&
    lhs.Kq_hat_2 == rhs.Kq_hat_2 &&
    lhs.rho_p == rhs.rho_p &&
    lhs.rho_q == rhs.rho_q &&
    lhs.delTau_p == rhs.delTau_p &&
    lhs.delTau_q == rhs.delTau_q &&
    lhs.moments == rhs.moments &&
    lhs.thrust == rhs.thrust &&
    lhs.M_hat == rhs.M_hat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_check::PlotDataMsg_<ContainerAllocator1> & lhs, const ::msg_check::PlotDataMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_check

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_check::PlotDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_check::PlotDataMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_check::PlotDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_check::PlotDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_check::PlotDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_check::PlotDataMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_check::PlotDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34437636d1c86e0bba868e7bc32517df";
  }

  static const char* value(const ::msg_check::PlotDataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34437636d1c86e0bULL;
  static const uint64_t static_value2 = 0xba868e7bc32517dfULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_check::PlotDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_check/PlotDataMsg";
  }

  static const char* value(const ::msg_check::PlotDataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_check::PlotDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Vector3 sp\n"
"geometry_msgs/Vector3 sq\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 angular_acceleration\n"
"geometry_msgs/Vector3 position_error\n"
"geometry_msgs/Vector3 velocity_error\n"
"geometry_msgs/Vector3 position_error_integral\n"
"geometry_msgs/Vector3 angle_error\n"
"geometry_msgs/Vector3 angle_rate_error\n"
"geometry_msgs/Vector3 Kp_hat\n"
"geometry_msgs/Vector3 Kq_hat_0\n"
"geometry_msgs/Vector3 Kq_hat_1\n"
"geometry_msgs/Vector3 Kq_hat_2\n"
"geometry_msgs/Vector3 rho_p\n"
"geometry_msgs/Vector3 rho_q\n"
"geometry_msgs/Vector3 delTau_p\n"
"geometry_msgs/Vector3 delTau_q\n"
"geometry_msgs/Vector3 moments\n"
"float64 thrust\n"
"float64 M_hat\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::msg_check::PlotDataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_check::PlotDataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sp);
      stream.next(m.sq);
      stream.next(m.acceleration);
      stream.next(m.angular_acceleration);
      stream.next(m.position_error);
      stream.next(m.velocity_error);
      stream.next(m.position_error_integral);
      stream.next(m.angle_error);
      stream.next(m.angle_rate_error);
      stream.next(m.Kp_hat);
      stream.next(m.Kq_hat_0);
      stream.next(m.Kq_hat_1);
      stream.next(m.Kq_hat_2);
      stream.next(m.rho_p);
      stream.next(m.rho_q);
      stream.next(m.delTau_p);
      stream.next(m.delTau_q);
      stream.next(m.moments);
      stream.next(m.thrust);
      stream.next(m.M_hat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlotDataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_check::PlotDataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_check::PlotDataMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sp: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.sp);
    s << indent << "sq: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.sq);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "angular_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_acceleration);
    s << indent << "position_error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position_error);
    s << indent << "velocity_error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_error);
    s << indent << "position_error_integral: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position_error_integral);
    s << indent << "angle_error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angle_error);
    s << indent << "angle_rate_error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angle_rate_error);
    s << indent << "Kp_hat: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Kp_hat);
    s << indent << "Kq_hat_0: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Kq_hat_0);
    s << indent << "Kq_hat_1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Kq_hat_1);
    s << indent << "Kq_hat_2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Kq_hat_2);
    s << indent << "rho_p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rho_p);
    s << indent << "rho_q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rho_q);
    s << indent << "delTau_p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.delTau_p);
    s << indent << "delTau_q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.delTau_q);
    s << indent << "moments: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.moments);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "M_hat: ";
    Printer<double>::stream(s, indent + "  ", v.M_hat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_CHECK_MESSAGE_PLOTDATAMSG_H
